# Generated by Django 4.2.11 on 2024-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="autor",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="publish_date",
            new_name="published_date",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="images/car.png", null=True, upload_to="images/"
            ),
        ),
    ]
